import sys
import os
import colorama
import time

def clear_screen():
    print('...')
    time.sleep(60)
    # Check the operating system and run the appropriate clear command
    if os.name == 'nt':  # Windows
        os.system('cls')
    else:  # macOS and Linux
        os.system('clear')

def ani(text, delay=0.06):
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(delay)
    print()  # Move to the next line

def inani(text, delay=0.06):
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(delay)
    input()  # Move to the next line



ani("Welcome to the game Consciousness! We hope that you have a wonderful experience!")
name= inani("What's your name?: ")
ani("<But you can't seem to remember>")
ani(" ")
ani("<You wake up to a place unfamiliar but familiar to yourself, the first thing you see? A sign>")
ani("'Welcome, you have one goal destroy all 4 dolls scattered across different rooms!'")
ani("'If you do... you'll get a prize! How about it?'")
choice1=input("Y/N?: ")


if choice1.lower() == "y":
    ani("  ")
    ani("'Very good...'")
    ani("[Your Consciousness feels content with this option]")
    ani("<As you look around, you see 4 different corridors with labels.>")
    ani ("'Kitchen - North'")
    ani("'Child's room - South'")
    ani("'Master Bedroom - East'")
    ani("'Garage - West'")
    ani("[You start to look to each path]")
    choice3=inani("N/S/W/E ('CHOOSE N'): ")
    if choice3 == "n" or "N":
        ani("  ")
        ani("<You walk along the carpet of the north hallway, following the path until you reach a bright yellow door.>")
        ani("<Do you wish to push open the door?>")
        ani("[Your Consciousness urges you to keep going, don't stop]")
        choice4= inani("Y/N?: ")
        if choice4 == "y" or "Y":
            ani("  ")
            ani("<You push open the door and look around>")
            ani("<You have a sudden pull to the counter>")
            ani("<A knife>")  
            ani("<Do you wish to take the knife?>")
            choice5=inani("Y/N?: ")
            if choice5 == "y" or "Y":
                ani("'Not like you had a choice anyways'")
                ani("  ")
                ani("<You hear a new voice along with your Consciousness... >")
                ani("|I'm sorry, I thought I could give you everything...|")
                ani("   ")
                ani("<You turn around from the counter and realise that there's a doll>")
                ani("<It's just standing>")
                ani("<Waiting>")
                ani("   ")
                ani("[Your consciousness urges you to destroy it]")
                ani("<You don't have a choice>")
                ani("    ")
                ani("|Why are you here?|")
                ani("|...|")
                ani("|I'm so sorry|")
                ani("  ")
                ani("<The doll gives you a riddle...>")
                ani("|What is the most important thing to a chef?|")
                ani("<Your choices: Their Knife (a); Their Skill (b); Their Workspace (c); Their Integrity (d)>")
                choice6=inani("<Your answer>: ")
                if choice6 == "a" or "A":
                    ani("  ")
                    ani("'You selected the correct answer!'")
                    ani("'Now you have one last thing to do'")
                    choice7=inani("'DO IT (Y/N): '")
                    if choice7 == "y" or "Y":
                        ani("|Why?|", delay=0.5)
                        ani("  ")
                        ani("<But the voice remains...>")
                        ani("|I tried my best|")
                        ani("  ")
                        ani("'You did such a good job'")
                        ani("[You need to keep moving]")
                        choice8= inani("S/W/E (Choose S): ")
                        if choice8 == "s" or "S":
                            ani("<You shakely walk out the yellow door and out into the room that started everything>")
                            ani("<You slowly walk towards the south hallway until you see the sign>")
                            ani("'Only 3 more to go :)'")
                            ani("[You feel wonderful]")
                            ani("<You feel unnerved>")
                            ani("  ")
                            ani("<This time you see a cute pastel blue door at the end of the hallway>")
                            ani("<It makes your heart ache>")
                            ani("   ")
                            choice9=inani("Go in? Y/N: ")
                            if choice9 == "y" or "Y":
                                ani("[:)]")
                                ani("<You push the door slightly and see a broken rattle>")
                                ani(" ")
                                ani("[You already have a knife]")
                                ani("<You push the door and see a sleeping child?")
                                ani("...", delay=0.25)
                                ani("<Not a child.>")
                                ani("[It's another doll! After this? Only 2 more!]")
                                ani("|...|")
                                ani("   ")
                                ani("'Well that's no fun. How about this? I'll give you a puzzle since they're sleeping!'")
                                choice10=inani("Y/N: ")
                                if choice10 == "y" or "Y":
                                    ani("'Great'")
                                    ani("'But i'll give you some time to explore... they're asleep anyways...'")
                                    choice11=inani("Explore? (Y/N): ")
                                    if choice11 == "y" or "Y":
                                        ani("'Sounds great, tell me when you're done'")
                                        ani("Where would you like to look?")
                                        ani("Closet, Bed, Toy shelf")
                                        choice12=inani("Choose...: ")
                                        if choice12 == "Closet" or "closet":
                                            ani("<You walk towards the closet>")
                                            ani("<Your heart hurts even more>")
                                            ani("|Do you remember?|", delay=0.2)
                                            ani("   ")
                                            choice13=inani("Attempt to open it? (Y/N): ")
                                            if choice13 == "y" or "Y":
                                                ani("<You open the closet and realise it's a door to a secret room>")
                                                ani("<There's a padlock with 4 digits on it>")
                                                ani("Do you want to try openning the door? You will only have one shot")
                                                ani("|...This is the least I can do for you|")
                                                ani("|3;8|")
                                                choice14=inani("Open the door? (Type the 4 digit code): ")
                                                if choice14 == "3684":
                                                    ani("<Your consciousness falls silent as you walk into your room>")
                                                    ani("<You know that once you leave, you'll die>")
                                                    ani("<He'll find you>")
                                                    ani("<Her voice is gone aswell>")
                                                    ani("<On the table is a diary, the name?>")
                                                    ani(name)
                                                    ani("<There's only one entry intact>")
                                                    ani("Read the entry?")
                                                    mychoice=inani("Y/N: ")
                                                    ani("But your no longer in control", delay=0.2)
                                                    ani("  ")
                                                    ani("<Dear Diary, I finally found a home!>")
                                                    ani("<I have a mum, a dad, and even a little brother! They even have a dog!>")
                                                    ani("<I finally have a family, a real family>")
                                                    ani("<I hope this happiness never ends>")
                                                    ani("         ", delay=1)
                                                    ani("<Complete the game>")
                                                    ani("<Complete Consciousness>")
                                                    ani("<Because once you do?>")
                                                    ani("<I can finally go home>")
                                                    clear_screen()
                                                else:
                                                    ani("You failed to open the door")
                                                    ani("[Keep moving]")
                                                    ani("  ")
                                                    ani("<You return to the ''childlike'' dolls bed>")
                                                    ani("<Beside the sleeping child is a paper puzzle>")
                                                    ani("   ")
                                                    ani("'I made sure to make the puzzle they intended to, with the responses you would have given'")
                                                    ani("  ")
                                                    ani("~Don't you recognize me? Don't you remember me?... Don't you love me?~", delay=0.35)
                                                    ani("<Your choices: ...;...;...;...;>")
                                                    choice16=inani("<Your answer>: ")
                                                    ani("~...~")
                                                    ani("'You selected the correct answer!'")
                                                    ani("  ")
                                                    ani("|Don't hurt him... please|")
                                                    ani("<...>")
                                                    ani("[But you had no choice]", delay=0.2)
                                                    ani("  ")
                                                    choice17=inani("[Only 2 more] (W/E) Choose W: ")
                                                    if choice17 == "W" or "w":
                                                        ani("<You have to keep moving, no point in stopping now>")
                                                        ani("<You know the consequences of failure>", delay=0.2)
                                                        ani("<You go back to the main room>")
                                                        ani("<You feel hatred towards yourself>")
                                                        ani("[You feel pride towards yourself]")
                                                        ani("<You feel sick towards the sign in the centre of the main room>")
                                                        ani("[You feel adoration towards the sign in the centre of the main room]")
                                                        ani("'Only 2 more to go, ;)'")
                                                        ani("  ")
                                                        ani("<You walk along the next hallway, this time, a dark green door awaits you>")
                                                        ani("|My room... our room|", delay=0.2)
                                                        ani("[Be careful]")
                                                        choice18=inani("Do you wish to open the door? (Y/N): ")
                                                        if choice18 == "Y" or "y":
                                                            ani("<You open the door, there doesn't seem to be anyone there>")
                                                            ani("[He's in the wardrobe]")
                                                            ani("[He knows what you did to his family]", delay=0.2)
                                                            ani("  ")
                                                            choice19=inani("Do you wish to explore or head to the wardrobe? (Explore/Wadrobe): ")
                                                            if choice19 == "Explore" or "explore":
                                                                ani("<You look around the room and see a drawer>")
                                                                choice20=inani("Open it? (Y/N): ")
                                                                if choice20 == "Y" or "y":
                                                                    ani("<You open the drawer to see a box, when opened? It's full of daggers>")
                                                                    ani("[You already have the knife]")
                                                                    ani("  ")
                                                                    ani("[There's nothing else to see]")
                                                                    ani("  ")
                                                                    ani("[You move away from the drawer and head towards the wardrobe]")
                                                                    ani("<You move away from the drawer and shakily head to the wardrobe>")
                                                                    ani("|They move away from the drawer and ---- head towards the wardrobe|")
                                                                    ani(" ")
                                                                    ani("-Why did you hurt them?-", delay=0.2)
                                                                    ani("  ")
                                                                    ani("<The sad doll gives you a puzzle>")
                                                                    ani("-What does every parent have/need to do?-")
                                                                    ani("<Your choices: Support(a); Nurture(b); Sacrifice(c); Love(d)>")
                                                                    choice21=inani("<Your answer>: ")
                                                                    if choice21 == "c" or "C":
                                                                        ani("'You selected the correct answer!'")
                                                                        ani(" ")
                                                                        ani("[You stab him happily]")
                                                                        ani("<You stab him regretfully>")
                                                                        ani("|They... They stab... They stab him with guilt|", delay=0.2)
                                                                        ani("  ")
                                                                        ani("[Keep moving]")
                                                                        ani("  ")
                                                                        ani("<Will this ever end?>", delay=0.2)
                                                                        ani("   ")

                                                                    else:
                                                                        ani("'Wrong answer!'")
                                                                        clear_screen()
                                                                else:
                                                                    ani("<Open the box, that's what they want>")
                                                                    clear_screen()
                                                            else:
                                                               ani("'You're such a party pooper'")
                                                               ani("  ")
                                                               ani("'⍓︎□︎◆︎ ♎︎♓︎♏︎♎︎'")
                                                               clear_screen() 
                                                        else:
                                                            ani("'The less you rebel the better'")
                                                            clear_screen()
                                                    else:
                                                        ani("'Don't try to escape me'")
                                                        ani("  ")
                                                        clear_screen()
                                            if choice13 == "N" or "n":
                                                ani("<Please try again... for me>", delay=0.2)
                                                clear_screen()
                                        if choice12 == "Bed" or "bed" or "Toy shelf" or "toy shelf" or "Toy Shelf":
                                            ani("<You approach, you stare, you reminisce...>")
                                            ani("<You remember>", delay=0.2)
                                            ani("<You look at the person beyond the screen...>", delay=0.2)
                                            ani("3684")
                                            ani("  ")
                                            ani("['We can't have that']")
                                            clear_screen()
                                        else:
                                            ani("'Wrong input'")
                                            clear_screen()
                                    else:
                                        ani("'You're such a party pooper'")
                                        ani("  ")
                                        ani("'⍓︎□︎◆︎ ♎︎♓︎♏︎♎︎'")
                                        clear_screen()
                            else:
                                ani("'Don't resist'")
                                ani("Don't resist")
                                ani("Don't resist", delay=0.2)
                                clear_screen()
                        else:
                            ani("'I told you to choose S'")
                            ani("You died...")
                            clear_screen()
                    else:
                        ani("'Did you think you had a choice?'")
                        ani("You died!")
                        clear_screen()
                else:
                    ani("'That's not the right answer'")
                    ani("You died, try again-")
                    clear_screen()

            if choice5 == "n" or "N":
                ani("  ")
                ani("'You might regret this later'")
                ani("[Your Consciousness is annoyed]")
                ani("   ")
                ani("<You turn around from the counter and realise that there's a doll>")
                ani("<It's just standing>")
                ani("<Waiting>")
                ani("   ")
                ani("[Your consciousness urges you to destroy it]")
                ani("<You don't have a choice>")
                ani("    ")
                ani("<You don't have a weapon...>")
                ani("  ")
                ani("YOU DIED?! YOU ♓♎︎♓︎□︎⧫︎", delay=0.07)
                clear_screen()
            else:
                ani("  ")
                ani("'Whelp... don't know how you failed that'")
                ani("   ")
                clear_screen()
        if choice4 == "n" or "N":
            ani("  ")
            ani("'That's not the right choice'")
            ani("[Try to keep moving]")
            ani("  ")
            ani("You died. How about you try again!")
            clear_screen()
        else:
            ani("  ")
            ani("'How'd you fail a simple Y/N?'")
            clear_screen()
    else:
        ani("  ")
        ani("'How'd you fail a simple instruction'")
        clear_screen()


if choice1.lower() == "n":
    ani("  ")
    ani("'Are you sure? The consequences for denial... are detrimental.'")
    ani("[Your Consciousness believes you made the wrong choice and to change it while you have the chance]")
    choice2=inani("Y/N? (CAPITAL): ")
    if choice2 == "N":
        ani("  ")
        ani("'You've made the right choice... But you made it too late'")
        ani("You died")
        ani("  ")
        ani("'♌︎♏︎⧫︎⧫︎♏︎❒︎ ■︎□︎⧫︎ ❍︎♋︎🙵♏︎ ⧫︎♒︎♏︎ ⬧︎♋︎❍︎♏︎ ❍︎♓︎⬧︎⧫︎♋︎🙵♏︎'")
        clear_screen()
    if choice2 == "Y":
        ani("  ")
        ani("'I warned you...'")
        ani("[You can't escape ♓︎⧫︎🕯︎⬧︎ ♑︎❒︎♓︎ ︎◻]")
        ani("  ")
        ani("Uh oh! You died! How about you try again?")
        clear_screen()
    if choice2 == "y" or "n":
        ani("  ")
        ani("'I told you to use a capital...'")
        ani("  ")
        ani("'︎♓♎︎♓︎□︎⧫︎'", delay=0.5)
        ani("  ")
        ani("[Your Consciousness is dissapointed in yourself]")
        ani("  ")
        ani("ERROR: YOU'VE BEEN KICKED OUT OF THE SYSTEM PLEASE RESTART")
        ani("<Rude>")
        clear_screen()
    else:
        ani("  ")
        ani("'⧫︎♒︎♋︎⧫︎🕯︎⬧︎ ■︎□︎⧫︎ ⧫︎♒︎ ︎♏⬧︎♍︎❒︎♓︎ ︎◻⧫︎...'", delay=0.2)
        ani("Your feeling unsettled")
        ani("  ")
        ani("You failed, restart the game to try again") 
        clear_screen()


else:
    ani("  ")
    ani("'⧫︎♒︎♋︎⧫︎🕯︎⬧︎ ■︎□︎⧫︎ ⧫︎♒︎ ︎♏⬧︎♍︎❒︎♓︎ ︎◻⧫︎...'", delay=0.2)
    ani("Your feeling unsettled")
    ani("  ")
    ani("You failed, restart the game to try again") 
    clear_screen()